// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

import { readFile, readdir, writeFile, mkdir, unlink } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Marked } from "marked";
import { format } from "prettier";
import { parse as parseYaml } from "yaml";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const GENERATED = "<!-- Generated by scripts/blog/build.mjs; edit website/blog/posts/*.md. -->";
const ORIGIN = "https://omnesis.dev";
// The docs chrome is the website's shared static navigation and footer.
const chrome = readFileSync(join(ROOT, "website/docs/index.html"), "utf8");
const nav = chrome
  .match(/<nav id="nav">[\s\S]*?<\/nav>/)[0]
  .replace('href="/docs/" aria-current="page"', 'href="/docs/"')
  .replace('href="/blog/"', 'href="/blog/" aria-current="page"')
  .replace('<ul class="nav-links">', '<ul class="nav-links" id="primary-navigation">')
  .replace(
    "        </div>\n      </div>\n    </nav>",
    `<button id="nav-burger" class="nav-burger" type="button" aria-label="Open navigation menu" aria-controls="primary-navigation" aria-expanded="false"><svg class="icon-open" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18" /></svg><svg class="icon-close" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M18 6 6 18M6 6l12 12" /></svg></button></div></div></nav>`,
  );
const footer = chrome.match(/<footer class="site-footer">[\s\S]*?<\/footer>/)[0];

export function escapeHtml(value) {
  return String(value).replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c],
  );
}

function safeUrl(value) {
  // Only explicit web links and site-relative references are allowed in Markdown.
  return (
    /^(?:https?:\/\/|\/(?!\/)|#)/i.test(value) &&
    !Array.from(value).some((character) => character.charCodeAt(0) <= 32 || character === "\\")
  );
}

const markdown = new Marked({
  gfm: true,
  renderer: {
    html({ text }) {
      return escapeHtml(text);
    },
    link({ href, title, tokens }) {
      const text = this.parser.parseInline(tokens);
      if (!safeUrl(href)) throw new Error(`Unsupported Markdown link: ${href}`);
      return `<a href="${escapeHtml(href)}"${title ? ` title="${escapeHtml(title)}"` : ""}>${text}</a>`;
    },
    image({ href, title, text }) {
      if (!safeUrl(href) || href.startsWith("#"))
        throw new Error(`Unsupported Markdown image: ${href}`);
      return `<img src="${escapeHtml(href)}" alt="${escapeHtml(text)}"${title ? ` title="${escapeHtml(title)}"` : ""} loading="lazy" />`;
    },
  },
});

export function parsePost(source, filename) {
  const slug = filename.replace(/\.md$/, "");
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) || slug === "index")
    throw new Error(`Invalid post filename: ${filename}`);
  // Parse metadata as data only; aliases cannot expand unbounded input.
  const match = source.replaceAll("\r\n", "\n").match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: expected YAML front matter between --- lines`);
  const meta = parseYaml(match[1], { maxAliasCount: 0, uniqueKeys: true });
  if (!meta || typeof meta !== "object" || Array.isArray(meta))
    throw new Error(`${filename}: metadata must be an object`);
  const allowed = new Set(["title", "description", "date", "author", "tags", "draft"]);
  if (Object.keys(meta).some((key) => !allowed.has(key)))
    throw new Error(`${filename}: unknown metadata field`);
  for (const key of ["title", "description", "author", "date"]) {
    if (typeof meta[key] !== "string" || !meta[key].trim())
      throw new Error(`${filename}: missing ${key}`);
  }
  if (
    !/^\d{4}-\d{2}-\d{2}$/.test(meta.date) ||
    !Number.isFinite(Date.parse(meta.date)) ||
    new Date(meta.date).toISOString().slice(0, 10) !== meta.date
  )
    throw new Error(`${filename}: invalid date`);
  if (meta.draft !== undefined && typeof meta.draft !== "boolean")
    throw new Error(`${filename}: draft must be a boolean`);
  if (
    meta.tags !== undefined &&
    (!Array.isArray(meta.tags) || meta.tags.some((tag) => typeof tag !== "string" || !tag.trim()))
  )
    throw new Error(`${filename}: tags must be nonempty strings`);
  const body = match[2].trim();
  if (!body) throw new Error(`${filename}: post body is empty`);
  if (markdown.lexer(body).some((token) => token.type === "heading" && token.depth === 1))
    throw new Error(`${filename}: use ## headings; title supplies the page's h1`);
  return { ...meta, slug, tags: meta.tags ?? [], draft: meta.draft ?? false, body };
}

export function renderMarkdown(body) {
  return markdown.parse(body);
}

function metadata(post) {
  const date = new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(post.date));
  const minutes = Math.max(1, Math.ceil(post.body.split(/\s+/).length / 220));
  return `<div class="post-meta"><span>${escapeHtml(post.author)}</span><time datetime="${post.date}">${date}</time><span>${minutes} min read</span></div>${post.tags.length ? `<div class="post-tags">${post.tags.map((tag) => `<span class="post-tag">${escapeHtml(tag)}</span>`).join("")}</div>` : ""}`;
}

function layout({ title, description, path, content, post, preview = false }) {
  const canonical = ORIGIN + path;
  const structured =
    post && !preview
      ? `<script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.description, datePublished: post.date, author: { "@type": "Person", name: post.author }, mainEntityOfPage: canonical, image: ORIGIN + "/og-image.png" }).replaceAll("<", "\\u003c")}</script>`
      : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<title>${escapeHtml(title)} — Omnesis</title><meta name="description" content="${escapeHtml(description)}" />
<link rel="canonical" href="${canonical}" /><meta property="og:title" content="${escapeHtml(title)} — Omnesis" />
<meta property="og:description" content="${escapeHtml(description)}" /><meta property="og:type" content="${post ? "article" : "website"}" />
<meta property="og:url" content="${canonical}" /><meta property="og:image" content="${ORIGIN}/og-image.png" />
<meta name="twitter:card" content="summary_large_image" />${post ? `<meta property="article:published_time" content="${post.date}" />` : ""}
<link rel="icon" type="image/svg+xml" href="/favicon.svg" /><link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<meta name="theme-color" content="#06090f" /><link rel="stylesheet" href="/docs/docs.css" /><link rel="stylesheet" href="/footer-social.css" /><link rel="stylesheet" href="/blog/blog.css" />
<script>(function(){try{document.documentElement.dataset.theme=localStorage.getItem("omnesis-theme")||(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark");}catch(e){document.documentElement.dataset.theme="dark";}})();</script>
${preview ? '<meta name="robots" content="noindex, nofollow" />' : ""}${structured}<script src="/blog/blog.js" defer></script></head><body class="blog-page">${GENERATED}
<a class="skip-link" href="#main">Skip to content</a>
${nav}
<main id="main" class="blog-shell">${preview ? '<p class="post-tag" role="status">Local preview · Includes unpublished posts. Save changes and refresh to update.</p>' : ""}${content}</main>
${footer}
</body></html>`;
}

export function renderIndex(posts, { preview = false } = {}) {
  const list = posts.length
    ? `<div class="post-list">${posts.map((post) => `<article class="post-card">${metadata(post)}<h2><a href="/blog/${post.slug}">${escapeHtml(post.title)}</a></h2><p class="post-description">${escapeHtml(post.description)}</p><a class="read-post" href="/blog/${post.slug}" aria-label="Read ${escapeHtml(post.title)}">Read post <span aria-hidden="true">→</span></a></article>`).join("")}</div>`
    : `<div class="empty-state"><span class="empty-mark" aria-hidden="true">01 /</span><h2>Posts coming soon.</h2></div>`;
  return layout({
    preview,
    title: "Blog",
    description:
      "Engineering notes on building Omnesis: problems, solutions, and the tradeoffs behind them.",
    path: "/blog/",
    content: `<header class="blog-intro"><p class="eyebrow">BUILDING OMNESIS</p><h1>Notes from the build.</h1><p class="lede">I’ll try to share updates and interesting stories of how I went about building Omnesis.</p></header>${list}`,
  });
}

export function renderPost(post, giscus, { preview = false } = {}) {
  const content = `<a class="back-link" href="/blog/">← All posts</a><article><header class="post-header"><p class="eyebrow">BUILDING OMNESIS</p><h1>${escapeHtml(post.title)}</h1><p class="post-deck">${escapeHtml(post.description)}</p>${metadata(post)}</header><div class="post-body">${renderMarkdown(post.body)}</div></article>
${
  preview
    ? '<p class="post-tag">Comments are disabled in local preview.</p>'
    : `<section id="comments" class="comments" aria-labelledby="comments-title" data-giscus-repo="${escapeHtml(giscus.repo)}" data-giscus-repo-id="${escapeHtml(giscus.repoId)}" data-giscus-category="${escapeHtml(giscus.category)}" data-giscus-category-id="${escapeHtml(giscus.categoryId)}" data-giscus-term="blog/${post.slug}">
<h2 id="comments-title">Join the discussion</h2><p>Comments and reactions are public and stored on GitHub. Sign in with GitHub to participate.</p><p>The comments widget connects to Giscus and GitHub when you load it. <a href="/privacy">Privacy details</a>.</p>
<button id="load-comments" type="button">Show comments &amp; reactions</button><p id="comments-status" role="status" aria-live="polite"></p><div id="giscus-container" class="giscus"></div>
<p class="discussion-link">You can also visit <a href="https://github.com/${escapeHtml(giscus.repo)}/discussions/categories/${escapeHtml(giscus.category.toLowerCase().replaceAll(" ", "-"))}">Blog comments on GitHub</a>.</p><noscript><p>Enable JavaScript to load comments, or visit <a href="https://github.com/${escapeHtml(giscus.repo)}/discussions/categories/${escapeHtml(giscus.category.toLowerCase().replaceAll(" ", "-"))}">GitHub Discussions</a>.</p></noscript></section>`
}`;
  return layout({
    preview,
    title: post.title,
    description: post.description,
    path: `/blog/${post.slug}`,
    content,
    post,
  });
}

export async function build({
  root = ROOT,
  check = false,
  today = new Date().toISOString().slice(0, 10),
} = {}) {
  const blog = join(root, "website/blog");
  const giscus = JSON.parse(await readFile(join(blog, "giscus.json"), "utf8"));
  for (const key of ["repo", "repoId", "category", "categoryId"])
    if (typeof giscus[key] !== "string" || !giscus[key].trim())
      throw new Error(`Missing Giscus ${key}`);
  if (!/^[\w.-]+\/[\w.-]+$/.test(giscus.repo)) throw new Error("Invalid Giscus repository");
  const files = (await readdir(join(blog, "posts"))).filter((file) => file.endsWith(".md")).sort();
  const posts = await Promise.all(
    files.map(async (file) => parsePost(await readFile(join(blog, "posts", file), "utf8"), file)),
  );
  const published = posts
    .filter((post) => !post.draft && post.date <= today)
    .sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
  const outputs = new Map([
    ["index.html", renderIndex(published)],
    ...published.map((post) => [`${post.slug}.html`, renderPost(post, giscus)]),
  ]);
  const changed = [];
  await mkdir(blog, { recursive: true });
  // A stale published draft or deleted post must not remain accessible at its old URL.
  for (const file of await readdir(blog)) {
    if (!file.endsWith(".html") || outputs.has(file)) continue;
    const old = await readFile(join(blog, file), "utf8");
    if (!old.includes(GENERATED))
      throw new Error(`Refusing to remove non-generated blog page: ${file}`);
    changed.push(file);
    if (!check) await unlink(join(blog, file));
  }
  for (const [file, html] of outputs) {
    const output = await format(html, { parser: "html", printWidth: 100 });
    const path = join(blog, file);
    const existing = await readFile(path, "utf8").catch((error) => {
      if (error.code === "ENOENT") return "";
      throw error;
    });
    if (existing !== output) {
      if (existing && !existing.includes(GENERATED))
        throw new Error(`Refusing to overwrite non-generated blog page: ${file}`);
      changed.push(file);
      if (!check) await writeFile(path, output);
    }
  }
  const sitemapPath = join(root, "website/sitemap.xml");
  const sitemap = await readFile(sitemapPath, "utf8");
  const block = `  <!-- blog:start -->\n${["/blog/", ...published.map((post) => `/blog/${post.slug}`)].map((path) => `  <url><loc>${ORIGIN}${path}</loc></url>`).join("\n")}\n  <!-- blog:end -->`;
  const next = sitemap.includes("<!-- blog:start -->")
    ? sitemap.replace(/ {2}<!-- blog:start -->[\s\S]*? {2}<!-- blog:end -->/, block)
    : sitemap.replace("</urlset>", `${block}\n</urlset>`);
  if (next !== sitemap) {
    changed.push("sitemap.xml");
    if (!check) await writeFile(sitemapPath, next);
  }
  if (check && changed.length)
    throw new Error(
      `Blog output is stale: ${changed.join(", ")}. Run node scripts/blog/build.mjs.`,
    );
  return { published: published.map((post) => post.slug), changed };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  build({ check: process.argv.includes("--check") })
    .then(({ published, changed }) => {
      process.stdout.write(
        `Blog: ${published.length} published post(s), ${changed.length} file(s) updated.\n`,
      );
    })
    .catch((error) => {
      process.stderr.write(`${error.message}\n`);
      process.exitCode = 1;
    });
}
