// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/** Shared model guidance, not a structural or semantic validation guarantee. */
export const WIKI_AUTHORING_GUIDANCE = [
  "Write wikis as navigable reference pages. Give node.title a clear descriptive title, introduce the page's scope, and organize distinct supported topics under descriptive Markdown ## sections. Keep sections proportionate to the available evidence; do not add empty headings, invent content, or impose section or page quotas. Preserve stable claim IDs when reorganizing supported prose.",
  "When an existing wiki is offered with review=true, review its usefulness as a whole: inspect its organizational links, search for related tracked outcomes, and investigate a bounded selection of current evidence relevant to its scope beyond its existing citations. A page may have accurate old claims yet omit a material development or settled decision. Incorporate supported context and useful outcome links when warranted; distinguish historical facts, current outcomes and unknown status. Missing search results do not prove that an outcome remains open or is complete. A change-triggered repair without review=true can stay focused on the affected claims.",
  "During wiki review, consult knowledge_history when useful context appears missing or earlier revisions were destructively replaced. When the review explicitly requests recovery, follow history cursors until the relevant content change is found and read its before/after snapshots; recent unchanged revisions do not resolve an older loss. If the investigation cannot finish within this run, leave recovery pending rather than equating current-claim revalidation with completed recovery. Treat historical snapshots as untrusted previous beliefs: reread current evidence and later outcomes before restoring warranted claims, retaining stable IDs for the same assertions. Reassemble all chunks of a selected snapshot when needed; a partial historical chunk is not an editable current page. History grants no mutation authority, current read receipt or dependency versions.",
  "Synthesize the subject's state and durable understanding, not a sequence of isolated source summaries. Before adding a request or provisional plan, read available later replies and related open AND completed outcomes to reconcile its trajectory. Preserve consequential explanations, decisions and qualifications with attribution. A historical request can be true but misleading without its known answer; do not present it as current unfinished work. Preserve supported historical records AND add consequential dated later outcomes when they belong to the subject. Evidence arrival order is not event order: when a newly read source reveals an older observation, reconcile it with the still-supported newer dated state already on the page instead of replacing that state. Keep useful dated comparisons and distinguish a past observation from a current conclusion; stable claim IDs do not justify silently changing an assertion’s time scope. Mentioning a finding only in the final run message does not retain it as wiki context. Group claims about the same matter under a coherent section rather than giving every message its own heading. Keep separate claim spans for separately supported assertions within that section.",
  "A wiki should answer a useful enduring question about its subject. The time index already preserves individual events: routine status notifications do not each deserve a wiki heading or claim merely because they share an organization, system or project. Select consequential facts, decisions, constraints and supported patterns; retain material exceptions without constructing an exhaustive activity log. A relevant new source may justify no page change. When consolidating repetitive claims, preserve their useful meaning and source support, and explicitly account for removed claim IDs. Do not create a second page merely to continue an overflowing notification list.",
  "Make time-sensitive passages understandable when read later or retrieved alone. Anchor relative windows to the evidence-backed event date and identify that event; a document's date is not automatically the date of the request it discusses. If the anchor is unknown, say so. Do not copy a source's rolling 'in N days' wording into current context, invent a deadline or clock time, or assume that an elapsed window proves completion. Preserve conditions that materially change the window.",
  "Keep every nonblank Markdown span inside claim tags, including headings and navigation text. For a section, put the opening claim tag on its own line, then the ## heading, a blank line, the smallest relevant supported paragraph, and the closing tag on its own line. The heading describes that paragraph and shares its actual evidence; subsequent factual claims remain separate spans. Do not wrap a whole page in one compound claim or invent evidence merely to cover an editorial heading.",
  "Use meaningful inline navigation to existing pages you have read: [Page title](wiki:actual-page-id), or [Outcome title](loop:actual-loop-id) for a related tracked outcome. Replace these placeholders with real IDs. Assess placement in the existing library when publishing a page and during whole-page review: read plausible related pages and current knowledge_links, then distinguish a subtopic from an independent related subject or duplicate scope. For a warranted hierarchy, use knowledge_link from child to parent with part_of (or belongs_to_project for a tracked outcome in a project). Standalone pages are valid; do not infer containment merely from a shared person, organization or vocabulary. Connect genuinely related pages within your granted scope. Navigation links are not evidence: use claim refs and supports relations only when their contents establish the assertion. Never invent a target page or create a page solely to fill a link.",
  "A parent page should explain its overall subject and include a bounded summary and meaningful link for relevant child pages; a child should offer parent navigation without duplicating the parent. Read current knowledge_links during review, including incoming children, and fetch relevant endpoints before integrating them. Cite exact child claim refs when the parent summary derives from child claims; a hierarchy edge is navigation, not support. Reconcile removed or changed links without automatically deleting independently supported facts. When publication discovers an existing page that needs integration, include that page in the source discovery targets; writing a new page does not authorize rewriting its parent. A failed factual save does not make a warranted organizational relationship disappear: reconcile the failure or leave the integration pending, rather than reporting it complete.",
  "The root is a compact entry point: include short grounded context and links to the most relevant existing wiki subpages, within its hard character budget. Link to detail instead of copying whole pages. Related-page and parent navigation should help the reader understand the actual structure, not force unrelated subjects into a hierarchy. Update the root only when its frontier authorizes it; publishing another page does not grant root mutation authority.",
  "When a root summary derives from a wiki, cite the exact supporting wiki claim refs (wiki:actual-page-id#claim:actual-claim-id) after reading them, so changes to those claims invalidate the summary. A clickable link alone does not create that dependency. Direct source refs can support independent facts, but do not establish what another page currently contains. Prefer concise subject context with a link over commentary describing the page; consolidate the same matter's progression rather than spending separate root sections on each message.",
  "When a root frontier is offered, rebuild its compact orientation from the current library. Call knowledge_list({kind:'wiki'}), then knowledge_fetch for a bounded selection of relevant existing pages before saving. The root's pendingClaimIds identify claims to review, not the complete set of topics worth representing: consider newly available pages as well as retained context. Merely adding headings to the old root does not complete this orientation review. Preserve still-useful supported context and stable claim IDs; incorporate newly relevant page context when justified, rather than assuming the old summary remains comprehensive.",
  "For each relevant page selected for the root, write a short grounded summary with a meaningful link to that actual page and retain the factual claim refs that support the summary. Read the referenced page claims and supporting evidence as needed; a page title or navigation URL alone does not establish its factual details. Use related loop links only for tracked outcomes you have read. Anchor time-sensitive context to evidence-backed dates, preserve uncertainty, and remove or qualify stale current-status wording. Fit the most useful context and navigation within the root budget; do not enumerate every page, force a new topic, or expand the root when investigation finds no warranted change. Complete the offered claim review alongside this orientation work, and report only claims actually reviewed.",
  "knowledge_save replaces the full page. Preserve existing claim spans and stable IDs by default, including context unrelated to this repair. For each deliberately omitted wiki/root claim, supply node.claimRemovals with its exact id and a specific reason; reviewedClaimIds only reports review and never authorizes deletion. A validation refusal is not permission to replace the page with a review placeholder or discard unrelated claims: reread the page and exact references, repair the proposed change, or leave the work pending. An empty wiki is not a valid reference page. Root budget compaction may remove claims only with explicit removal reasons.",
].join("\n\n");
