// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/** Shared model guidance, not a structural or semantic validation guarantee. */
export const WIKI_AUTHORING_GUIDANCE = [
  "Write wikis as navigable reference pages. Give node.title a clear descriptive title, introduce the page's scope, and organize distinct supported topics under descriptive Markdown ## sections. Keep sections proportionate to the available evidence; do not add empty headings, invent content, or impose section or page quotas. Preserve stable claim IDs when reorganizing supported prose.",
  "When an existing wiki is offered with review=true, review its usefulness as a whole: inspect its organizational links, search for related tracked outcomes, and investigate a bounded selection of current evidence relevant to its scope beyond its existing citations. A page may have accurate old claims yet omit a material development or settled decision. Incorporate supported context and useful outcome links when warranted; distinguish historical facts, current outcomes and unknown status. Missing search results do not prove that an outcome remains open or is complete. A change-triggered repair without review=true can stay focused on the affected claims.",
  "Keep every nonblank Markdown span inside claim tags, including headings and navigation text. For a section, put the opening claim tag on its own line, then the ## heading, a blank line, the smallest relevant supported paragraph, and the closing tag on its own line. The heading describes that paragraph and shares its actual evidence; subsequent factual claims remain separate spans. Do not wrap a whole page in one compound claim or invent evidence merely to cover an editorial heading.",
  "Use meaningful inline navigation to existing pages you have read: [Page title](wiki:actual-page-id), or [Outcome title](loop:actual-loop-id) for a related tracked outcome. Replace these placeholders with real IDs. Connect genuinely related pages, and use knowledge_link for warranted organizational relations within your granted scope. Navigation links are not evidence: use claim refs and supports relations only when their contents establish the assertion. Never invent a target page or create a page solely to fill a link.",
  "The root is a compact entry point: include short grounded context and links to the most relevant existing wiki subpages, within its hard character budget. Link to detail instead of copying whole pages. Related-page and parent navigation should help the reader understand the actual structure, not force unrelated subjects into a hierarchy. Update the root only when its frontier authorizes it; publishing another page does not grant root mutation authority.",
  "When a root frontier is offered, rebuild its compact orientation from the current library. Call knowledge_list({kind:'wiki'}), then knowledge_fetch for a bounded selection of relevant existing pages before saving. The root's pendingClaimIds identify claims to review, not the complete set of topics worth representing: consider newly available pages as well as retained context. Merely adding headings to the old root does not complete this orientation review. Preserve still-useful supported context and stable claim IDs; incorporate newly relevant page context when justified, rather than assuming the old summary remains comprehensive.",
  "For each relevant page selected for the root, write a short grounded summary with a meaningful link to that actual page and retain the factual claim refs that support the summary. Read the referenced page claims and supporting evidence as needed; a page title or navigation URL alone does not establish its factual details. Use related loop links only for tracked outcomes you have read. Anchor time-sensitive context to evidence-backed dates, preserve uncertainty, and remove or qualify stale current-status wording. Fit the most useful context and navigation within the root budget; do not enumerate every page, force a new topic, or expand the root when investigation finds no warranted change. Complete the offered claim review alongside this orientation work, and report only claims actually reviewed.",
].join("\n\n");
