// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/**
 * TypeScript transcription of the iOS Apple Health analytics schemas.
 *
 * Source of truth: `ios/Sources/Omnesis/AppleHealth/Schemas.swift`. Keep this
 * file in sync when iOS adds a new HealthCategory or column — the synthetic
 * desktop source must declare schemas with the same shape so a portal /
 * gateway can render data from either the iOS source or the synth twin
 * without source-specific code.
 */
import type { AnalyticsTableSchema, ColumnDefinition } from "@omnesis/source-sdk";

const METRIC_SLUGS = {
  body: ["body_mass", "body_fat_pct", "lean_mass", "bmi", "waist", "height"],
  activity: [
    "steps",
    "distance_walk_run",
    "distance_cycle",
    "distance_swim",
    "active_kcal",
    "basal_kcal",
    "exercise_minutes",
    "stand_minutes",
    "flights",
    "vo2max",
    "walking_speed",
    "walking_step_length",
    "walking_asymmetry_pct",
    "walking_double_support_pct",
    "stair_ascent_speed",
    "stair_descent_speed",
    "six_minute_walk_distance",
    "walking_steadiness",
  ],
  vitals: [
    "heart_rate",
    "resting_hr",
    "hrv",
    "bp_systolic",
    "bp_diastolic",
    "spo2",
    "blood_glucose",
    "body_temperature",
    "respiratory_rate",
    "afib_burden",
    "hr_recovery_1min",
    "walking_hr_avg",
  ],
  nutrition: [
    "energy_kcal",
    "protein_g",
    "carbs_g",
    "fat_g",
    "sugar_g",
    "fiber_g",
    "water_ml",
    "caffeine_mg",
    "vitamin_a",
    "vitamin_b1",
    "vitamin_b2",
    "vitamin_b3",
    "vitamin_b5",
    "vitamin_b6",
    "vitamin_b7",
    "vitamin_b9_folate",
    "vitamin_b12",
    "vitamin_c",
    "vitamin_d",
    "vitamin_e",
    "vitamin_k",
    "calcium",
    "iron",
    "magnesium",
    "potassium",
    "sodium",
    "zinc",
    "selenium",
    "copper",
    "manganese",
    "phosphorus",
    "chromium",
    "molybdenum",
    "iodine",
    "chloride",
  ],
  environment: ["env_audio_db", "headphone_audio_db"],
} satisfies Record<string, string[]>;

// Exact phrases produced by iOS `humanizeHealthIdentifier(TypeCatalog.identifier)`.
// Keep this twin in lockstep so synthetic compiler tests exercise live vocabulary.
const METRIC_IDENTIFIER_ALIASES: Record<string, string> = {
  body_mass: "body mass",
  body_fat_pct: "body fat percentage",
  lean_mass: "lean body mass",
  bmi: "body mass index",
  waist: "waist circumference",
  height: "height",
  steps: "step count",
  distance_walk_run: "distance walking running",
  distance_cycle: "distance cycling",
  distance_swim: "distance swimming",
  active_kcal: "active energy burned",
  basal_kcal: "basal energy burned",
  exercise_minutes: "apple exercise time",
  stand_minutes: "apple stand time",
  flights: "flights climbed",
  vo2max: "vo2 max",
  walking_speed: "walking speed",
  walking_step_length: "walking step length",
  walking_asymmetry_pct: "walking asymmetry percentage",
  walking_double_support_pct: "walking double support percentage",
  stair_ascent_speed: "stair ascent speed",
  stair_descent_speed: "stair descent speed",
  six_minute_walk_distance: "six minute walk test distance",
  walking_steadiness: "apple walking steadiness",
  heart_rate: "heart rate",
  resting_hr: "resting heart rate",
  hrv: "heart rate variability sdnn",
  bp_systolic: "blood pressure systolic",
  bp_diastolic: "blood pressure diastolic",
  spo2: "oxygen saturation",
  blood_glucose: "blood glucose",
  body_temperature: "body temperature",
  respiratory_rate: "respiratory rate",
  afib_burden: "atrial fibrillation burden",
  hr_recovery_1min: "heart rate recovery one minute",
  walking_hr_avg: "walking heart rate average",
  energy_kcal: "dietary energy consumed",
  protein_g: "dietary protein",
  carbs_g: "dietary carbohydrates",
  fat_g: "dietary fat total",
  sugar_g: "dietary sugar",
  fiber_g: "dietary fiber",
  water_ml: "dietary water",
  caffeine_mg: "dietary caffeine",
  vitamin_a: "dietary vitamin a",
  vitamin_b1: "dietary thiamin",
  vitamin_b2: "dietary riboflavin",
  vitamin_b3: "dietary niacin",
  vitamin_b5: "dietary pantothenic acid",
  vitamin_b6: "dietary vitamin b6",
  vitamin_b7: "dietary biotin",
  vitamin_b9_folate: "dietary folate",
  vitamin_b12: "dietary vitamin b12",
  vitamin_c: "dietary vitamin c",
  vitamin_d: "dietary vitamin d",
  vitamin_e: "dietary vitamin e",
  vitamin_k: "dietary vitamin k",
  calcium: "dietary calcium",
  iron: "dietary iron",
  magnesium: "dietary magnesium",
  potassium: "dietary potassium",
  sodium: "dietary sodium",
  zinc: "dietary zinc",
  selenium: "dietary selenium",
  copper: "dietary copper",
  manganese: "dietary manganese",
  phosphorus: "dietary phosphorus",
  chromium: "dietary chromium",
  molybdenum: "dietary molybdenum",
  iodine: "dietary iodine",
  chloride: "dietary chloride",
  env_audio_db: "environmental audio exposure",
  headphone_audio_db: "headphone audio exposure",
};

const METRIC_ALIAS_OVERRIDES: Record<string, string[]> = {
  body_mass: ["body mass", "weight"],
  body_fat_pct: ["body fat percentage"],
  lean_mass: ["lean body mass"],
  bmi: ["body mass index"],
  waist: ["waist circumference"],
  steps: ["step count"],
  distance_walk_run: ["walking and running distance", "walking running distance"],
  distance_cycle: ["cycling distance"],
  distance_swim: ["swimming distance"],
  active_kcal: ["active calories", "active energy burned"],
  basal_kcal: ["basal calories", "basal energy burned"],
  exercise_minutes: ["exercise time"],
  stand_minutes: ["stand time"],
  flights: ["flights climbed"],
  walking_asymmetry_pct: ["walking asymmetry percentage"],
  walking_double_support_pct: ["walking double support percentage"],
  six_minute_walk_distance: ["six minute walk test distance"],
  walking_steadiness: ["apple walking steadiness"],
  resting_hr: ["resting heart rate"],
  hrv: ["heart rate variability", "hrv"],
  bp_systolic: ["systolic blood pressure"],
  bp_diastolic: ["diastolic blood pressure"],
  spo2: ["blood oxygen", "oxygen saturation", "spo2"],
  vo2max: ["vo2 max"],
  afib_burden: ["afib burden", "atrial fibrillation burden"],
  hr_recovery_1min: ["one minute heart rate recovery"],
  walking_hr_avg: ["walking heart rate average"],
  energy_kcal: ["dietary energy consumed"],
  protein_g: ["dietary protein"],
  carbs_g: ["dietary carbohydrates"],
  fat_g: ["dietary fat total"],
  sugar_g: ["dietary sugar"],
  fiber_g: ["dietary fiber"],
  water_ml: ["dietary water"],
  caffeine_mg: ["dietary caffeine"],
  vitamin_b1: ["thiamin"],
  vitamin_b2: ["riboflavin"],
  vitamin_b3: ["niacin"],
  vitamin_b5: ["pantothenic acid"],
  vitamin_b7: ["biotin"],
  vitamin_b9_folate: ["folate"],
  env_audio_db: ["environmental audio exposure"],
  headphone_audio_db: ["headphone audio exposure"],
};

const WORKOUT_ALIASES: Record<string, string[]> = {
  cycling: ["cycle", "cycling", "bike ride"],
  functional_strength: ["functional strength"],
  hiking: ["hike", "hiking"],
  hiit: ["high intensity interval training", "hiit"],
  rowing: ["row", "rowing"],
  running: ["run", "running"],
  strength: ["strength training"],
  swimming: ["swim", "swimming"],
  walking: ["walk", "walking"],
};

const metricAliasesFor = (category: keyof typeof METRIC_SLUGS): Record<string, string[]> =>
  Object.fromEntries(
    METRIC_SLUGS[category].map((slug) => [
      slug,
      [
        ...new Set([
          slug.replaceAll("_", " "),
          ...(METRIC_IDENTIFIER_ALIASES[slug] ? [METRIC_IDENTIFIER_ALIASES[slug]] : []),
          ...(METRIC_ALIAS_OVERRIDES[slug] ?? []),
        ]),
      ].sort(),
    ]),
  );

const rowPerSampleColumns = (category: keyof typeof METRIC_SLUGS): ColumnDefinition[] => [
  { name: "id", type: "VARCHAR", description: "HealthKit sample UUID" },
  { name: "account_id", type: "VARCHAR", description: "Per-iPhone identifier (ios-<uuid>)" },
  {
    name: "metric",
    type: "VARCHAR",
    description: "HealthKit identifier (e.g. HKQuantityTypeIdentifierBodyMass)",
  },
  {
    name: "metric_slug",
    type: "VARCHAR",
    description: "Machine-readable short name (e.g. body_mass)",
    allowedValues: [...METRIC_SLUGS[category]].sort(),
    valueAliases: metricAliasesFor(category),
    categoricalRole: "series",
  },
  {
    name: "value",
    type: "DOUBLE",
    description: "Numeric reading in canonical unit",
    nullable: true,
  },
  {
    name: "unit",
    type: "VARCHAR",
    description: "Canonical unit (kg, bpm, m, ...)",
    nullable: true,
  },
  { name: "start_time", type: "TIMESTAMPTZ", description: "Sample start time (UTC)" },
  { name: "end_time", type: "TIMESTAMPTZ", description: "Sample end time (UTC)" },
  {
    name: "source_app",
    type: "VARCHAR",
    description: "Bundle id of the writing app",
    nullable: true,
  },
  { name: "source_device", type: "VARCHAR", description: "Source device name", nullable: true },
  { name: "metadata", type: "JSON", description: "Raw HealthKit metadata dict", nullable: true },
];

export const HEALTH_BODY: AnalyticsTableSchema = {
  tableName: "health_body",
  displayName: "Body Composition",
  description: "Body mass, body fat, lean mass, BMI, height, waist circumference.",
  columns: rowPerSampleColumns("body"),
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["metric_slug"],
    keyColumns: ["metric_slug", "value", "unit", "start_time"],
  },
  exampleQueries: [
    "SELECT metric_slug, ROUND(AVG(value),2) AS avg FROM health_body WHERE start_time >= CURRENT_DATE - INTERVAL 30 DAY GROUP BY metric_slug",
    "SELECT start_time, value FROM health_body WHERE metric_slug = 'body_mass' ORDER BY start_time DESC LIMIT 30",
  ],
};

export const HEALTH_ACTIVITY: AnalyticsTableSchema = {
  tableName: "health_activity",
  displayName: "Activity & Movement",
  description: "Steps, distance, calories, exercise minutes, stand time, flights climbed, VO2 max.",
  columns: rowPerSampleColumns("activity"),
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["metric_slug"],
    keyColumns: ["metric_slug", "value", "unit", "start_time"],
  },
  exampleQueries: [
    "SELECT date_trunc('day', start_time) AS day, SUM(value) FROM health_activity WHERE metric_slug = 'steps' GROUP BY day ORDER BY day DESC LIMIT 14",
  ],
};

export const HEALTH_VITALS: AnalyticsTableSchema = {
  tableName: "health_vitals",
  displayName: "Vitals",
  description: "Heart rate, HRV, blood pressure, SpO2, glucose, temperature, respiratory rate.",
  columns: rowPerSampleColumns("vitals"),
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["metric_slug"],
    keyColumns: ["metric_slug", "value", "unit", "start_time"],
  },
  exampleQueries: [
    "SELECT date_trunc('day', start_time) AS day, ROUND(AVG(value),0) AS avg_hr FROM health_vitals WHERE metric_slug = 'heart_rate' GROUP BY day ORDER BY day DESC LIMIT 30",
  ],
};

export const HEALTH_NUTRITION: AnalyticsTableSchema = {
  tableName: "health_nutrition",
  displayName: "Nutrition",
  description: "Macros, water, caffeine.",
  columns: rowPerSampleColumns("nutrition"),
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["metric_slug"],
    keyColumns: ["metric_slug", "value", "unit", "start_time"],
  },
  exampleQueries: [
    "SELECT date_trunc('day', start_time) AS day, SUM(value) FROM health_nutrition WHERE metric_slug = 'protein_g' GROUP BY day ORDER BY day DESC LIMIT 14",
  ],
};

export const HEALTH_ENVIRONMENT: AnalyticsTableSchema = {
  tableName: "health_environment",
  displayName: "Environmental exposure",
  description: "Ambient / headphone audio exposure.",
  columns: rowPerSampleColumns("environment"),
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["metric_slug"],
    keyColumns: ["metric_slug", "value", "unit", "start_time"],
  },
};

export const HEALTH_SLEEP: AnalyticsTableSchema = {
  tableName: "health_sleep",
  displayName: "Sleep",
  description: "Sleep stages as reported by Apple Watch, third-party wearables, or manual entry.",
  columns: [
    { name: "id", type: "VARCHAR", description: "HealthKit sample UUID" },
    { name: "account_id", type: "VARCHAR", description: "Per-iPhone identifier" },
    {
      name: "stage",
      type: "VARCHAR",
      description: "inBed / asleepUnspecified / asleepCore / asleepDeep / asleepREM / awake",
      allowedValues: [
        "inBed",
        "asleepUnspecified",
        "asleepCore",
        "asleepDeep",
        "asleepREM",
        "awake",
      ],
      valueAliases: {
        inBed: ["in bed"],
        asleepUnspecified: ["unspecified sleep"],
        asleepCore: ["core sleep"],
        asleepDeep: ["deep sleep"],
        asleepREM: ["rem", "rem sleep"],
        awake: ["awake"],
      },
      categoricalRole: "selector",
    },
    { name: "start_time", type: "TIMESTAMPTZ", description: "Stage start (UTC)" },
    { name: "end_time", type: "TIMESTAMPTZ", description: "Stage end (UTC)" },
    {
      name: "source_app",
      type: "VARCHAR",
      description: "Writing app bundle id",
      nullable: true,
    },
    { name: "source_device", type: "VARCHAR", description: "Source device", nullable: true },
    { name: "metadata", type: "JSON", description: "Raw HealthKit metadata", nullable: true },
  ],
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: { titleColumns: ["stage"], keyColumns: ["stage", "start_time", "end_time"] },
  exampleQueries: [
    "SELECT date_trunc('day', start_time) AS night, SUM(date_diff('minute', start_time, end_time))/60.0 AS hours FROM health_sleep WHERE stage IN ('asleepCore','asleepDeep','asleepREM','asleepUnspecified') GROUP BY night ORDER BY night DESC LIMIT 14",
  ],
};

export const HEALTH_MINDFUL: AnalyticsTableSchema = {
  tableName: "health_mindful",
  displayName: "Mindful Minutes",
  description: "Mindfulness / meditation sessions.",
  columns: [
    { name: "id", type: "VARCHAR", description: "HealthKit sample UUID" },
    { name: "account_id", type: "VARCHAR", description: "Per-iPhone identifier" },
    { name: "start_time", type: "TIMESTAMPTZ", description: "Session start (UTC)" },
    { name: "end_time", type: "TIMESTAMPTZ", description: "Session end (UTC)" },
    { name: "duration_seconds", type: "INTEGER", description: "Session duration" },
    {
      name: "source_app",
      type: "VARCHAR",
      description: "Writing app bundle id",
      nullable: true,
    },
    { name: "source_device", type: "VARCHAR", description: "Source device", nullable: true },
    { name: "metadata", type: "JSON", description: "Raw HealthKit metadata", nullable: true },
  ],
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["start_time"],
    titleTemplate: "Mindful session",
    keyColumns: ["start_time", "end_time", "duration_seconds"],
  },
};

export const HEALTH_WORKOUTS: AnalyticsTableSchema = {
  tableName: "health_workouts",
  displayName: "Workouts",
  description: "Runs, rides, swims, strength sessions, and anything else logged as an HKWorkout.",
  columns: [
    { name: "id", type: "VARCHAR", description: "HKWorkout UUID" },
    { name: "account_id", type: "VARCHAR", description: "Per-iPhone identifier" },
    {
      name: "workout_type",
      type: "VARCHAR",
      description: "running / cycling / swimming / hiking / etc.",
      canonicalValues: [
        "cycling",
        "elliptical",
        "functional_strength",
        "hiking",
        "hiit",
        "other",
        "rowing",
        "running",
        "strength",
        "swimming",
        "unknown",
        "walking",
        "yoga",
      ],
      valueAliases: WORKOUT_ALIASES,
      categoricalRole: "selector",
    },
    { name: "start_time", type: "TIMESTAMPTZ", description: "Workout start (UTC)" },
    { name: "end_time", type: "TIMESTAMPTZ", description: "Workout end (UTC)" },
    { name: "duration_seconds", type: "INTEGER", description: "Duration" },
    {
      name: "total_distance_m",
      type: "DOUBLE",
      description: "Distance in meters",
      nullable: true,
    },
    {
      name: "total_energy_kcal",
      type: "DOUBLE",
      description: "Active kilocalories",
      nullable: true,
    },
    {
      name: "source_app",
      type: "VARCHAR",
      description: "Writing app bundle id",
      nullable: true,
    },
    { name: "source_device", type: "VARCHAR", description: "Source device", nullable: true },
    { name: "metadata", type: "JSON", description: "Raw HealthKit metadata", nullable: true },
  ],
  primaryKey: ["id"],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["workout_type"],
    keyColumns: ["workout_type", "start_time", "duration_seconds", "total_distance_m"],
  },
};

export const HEALTH_MOOD: AnalyticsTableSchema = {
  tableName: "health_mood",
  displayName: "State of Mind",
  description:
    "Momentary emotions and daily mood reflections logged in Apple Health's Mental Wellbeing feature.",
  columns: [
    { name: "id", type: "VARCHAR", description: "HealthKit sample UUID" },
    { name: "account_id", type: "VARCHAR", description: "Per-iPhone identifier" },
    {
      name: "kind",
      type: "VARCHAR",
      description: "momentaryEmotion (in-the-moment) or dailyMood (reflection on the day)",
      allowedValues: ["momentaryEmotion", "dailyMood", "unknown"],
      valueAliases: {
        momentaryEmotion: ["momentary emotion"],
        dailyMood: ["daily mood"],
        unknown: ["unknown"],
      },
      categoricalRole: "selector",
    },
    {
      name: "valence",
      type: "DOUBLE",
      description: "Self-reported pleasantness from -1 to +1",
    },
    {
      name: "labels",
      type: "VARCHAR[]",
      description: "Felt-experience descriptors",
    },
    {
      name: "associations",
      type: "VARCHAR[]",
      description: "Life-context associations",
    },
    { name: "start_time", type: "TIMESTAMPTZ", description: "Log time (UTC)" },
    { name: "end_time", type: "TIMESTAMPTZ", description: "Log time (UTC)" },
    {
      name: "source_app",
      type: "VARCHAR",
      description: "Bundle id of the writing app",
      nullable: true,
    },
  ],
  primaryKey: ["id"],
  exampleQueries: [
    "SELECT date_trunc('day', start_time) AS day, ROUND(AVG(valence),2) AS avg_valence FROM health_mood GROUP BY day ORDER BY day DESC LIMIT 30",
  ],
  semanticTimeColumn: "start_time",
  record: {
    titleColumns: ["kind"],
    keyColumns: ["kind", "valence", "start_time"],
  },
  boundDocument: { externalIdColumns: ["id"] },
};

export const ALL_HEALTH_SCHEMAS: AnalyticsTableSchema[] = [
  HEALTH_BODY,
  HEALTH_ACTIVITY,
  HEALTH_VITALS,
  HEALTH_SLEEP,
  HEALTH_NUTRITION,
  HEALTH_MINDFUL,
  HEALTH_ENVIRONMENT,
  HEALTH_WORKOUTS,
  HEALTH_MOOD,
];
