// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/**
 * Daemon subcommands — the single `omnesis` binary is both the thin HTTP
 * client and the host for the long-lived processes:
 *
 *   omnesis gateway serve   → boots the gateway in-process
 *   omnesis collector run   → boots the collector in-process
 *
 * These are what the service units generated by `omnesis service install`
 * exec. Both run in the foreground and never resolve: the daemon owns the
 * process (signal handling, exit codes) from the moment it boots, and the
 * pending promise keeps the CLI wrapper's final `process.exit()` from ever
 * running. `index.ts` disables the runCli SIGINT-exit for these commands so
 * Ctrl-C reaches the daemon's own graceful-shutdown handlers.
 */

import { defineCommand } from "citty";

export const gatewayCommand = defineCommand({
  meta: {
    name: "gateway",
    description: "Run the Omnesis gateway",
  },
  subCommands: {
    serve: defineCommand({
      meta: {
        name: "serve",
        description: "Start the gateway daemon (foreground; supervise with `omnesis service`)",
      },
      run: async () => {
        // The gateway boots on import (module top-level) and registers its
        // own SIGINT/SIGTERM graceful-shutdown handlers.
        await import("@omnesis/gateway");
        await new Promise<never>(() => {});
      },
    }),
  },
});

export const collectorCommand = defineCommand({
  meta: {
    name: "collector",
    description: "Run the Omnesis collector",
  },
  subCommands: {
    run: defineCommand({
      meta: {
        name: "run",
        description: "Start the collector daemon (foreground; supervise with `omnesis service`)",
      },
      run: async () => {
        const { main } = await import("@omnesis/collector/main");
        // main() returns once startup completes; the sync engine keeps the
        // process alive. Hold the command open so the CLI never exits.
        await main();
        await new Promise<never>(() => {});
      },
    }),
  },
});
