// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

import { describe, expect, test } from "vitest";
import { transformManifest } from "./transform-manifest.mjs";

const VERSION = "0.2.0";

describe("transformManifest", () => {
  test("rewrites main/types to dist and pins workspace deps", () => {
    const out = transformManifest(
      {
        name: "@omnesis/config",
        version: VERSION,
        type: "module",
        main: "src/index.ts",
        types: "src/index.ts",
        exports: { ".": "./src/index.ts" },
        files: ["dist"],
        dependencies: { zod: "^3.23", "@omnesis/types": "*" },
        devDependencies: { vitest: "^4" },
        scripts: { dev: "tsx watch src/index.ts" },
      },
      VERSION,
    );
    expect(out.main).toBe("./dist/index.js");
    expect(out.types).toBe("./dist/index.d.ts");
    expect(out.exports["."]).toEqual({ types: "./dist/index.d.ts", default: "./dist/index.js" });
    expect(out.dependencies["@omnesis/types"]).toBe(VERSION);
    expect(out.dependencies.zod).toBe("^3.23");
    expect(out.devDependencies).toBeUndefined();
    expect(out.scripts).toBeUndefined();
    expect(out.publishConfig).toEqual({ access: "restricted" });
    expect(out.license).toBe("AGPL-3.0-or-later");
  });

  test("rewrites subpath exports", () => {
    const out = transformManifest(
      {
        name: "@omnesis/core",
        version: VERSION,
        exports: {
          ".": "./src/index.ts",
          "./protocol": "./src/subpath/protocol.ts",
        },
      },
      VERSION,
    );
    expect(out.exports["./protocol"]).toEqual({
      types: "./dist/subpath/protocol.d.ts",
      default: "./dist/subpath/protocol.js",
    });
  });

  test("rewrites bin entries", () => {
    const out = transformManifest(
      { name: "omnesis", version: VERSION, bin: { omnesis: "src/index.ts" } },
      VERSION,
    );
    expect(out.bin).toEqual({ omnesis: "./dist/index.js" });
  });

  test("keeps the native runtime preflight only on the published gateway", () => {
    const gateway = transformManifest({ name: "@omnesis/gateway", version: VERSION }, VERSION);
    const cli = transformManifest({ name: "omnesis", version: VERSION }, VERSION);
    expect(gateway.scripts).toEqual({ preinstall: "node native-runtime-preflight.mjs" });
    expect(gateway.files).toEqual(["native-runtime-preflight.mjs"]);
    expect(cli.scripts).toBeUndefined();
  });

  test("refuses private packages", () => {
    expect(() =>
      transformManifest({ name: "@omnesis/near-dupes", version: VERSION, private: true }, VERSION),
    ).toThrow(/private/);
  });

  test("refuses non-wildcard workspace deps", () => {
    expect(() =>
      transformManifest(
        { name: "@omnesis/x", version: VERSION, dependencies: { "@omnesis/core": "^0.1.0" } },
        VERSION,
      ),
    ).toThrow(/must be "\*" or the current prerelease version/);
  });

  test("accepts the exact workspace pins generated by Changesets prerelease mode", () => {
    const prerelease = "0.3.0-beta.0";
    const out = transformManifest(
      {
        name: "@omnesis/x",
        version: prerelease,
        dependencies: { "@omnesis/core": prerelease },
      },
      prerelease,
    );
    expect(out.dependencies["@omnesis/core"]).toBe(prerelease);

    expect(() =>
      transformManifest(
        {
          name: "@omnesis/x",
          version: prerelease,
          dependencies: { "@omnesis/core": "0.3.0-beta.1" },
        },
        prerelease,
      ),
    ).toThrow(/current prerelease version/);

    expect(() =>
      transformManifest(
        {
          name: "@omnesis/x",
          version: VERSION,
          dependencies: { "@omnesis/core": VERSION },
        },
        VERSION,
      ),
    ).toThrow(/current prerelease version/);

    expect(() =>
      transformManifest(
        {
          name: "@omnesis/x",
          version: "0.2.0-beta.0",
          dependencies: { "@omnesis/core": prerelease },
        },
        prerelease,
      ),
    ).toThrow(/current prerelease version/);
  });

  test("refuses entries outside src/*.ts", () => {
    expect(() =>
      transformManifest({ name: "@omnesis/x", version: VERSION, main: "lib/index.js" }, VERSION),
    ).toThrow(/expected a src\/\*\.ts path/);
  });

  test("leaves dev manifest untouched (pure)", () => {
    const pkg = { name: "@omnesis/config", version: VERSION, main: "src/index.ts" };
    transformManifest(pkg, VERSION);
    expect(pkg.main).toBe("src/index.ts");
  });

  test("access option can explicitly switch publishConfig to public", () => {
    const out = transformManifest(
      { name: "@omnesis/config", version: VERSION, main: "src/index.ts" },
      VERSION,
      { access: "public" },
    );
    expect(out.publishConfig).toEqual({ access: "public" });
  });
});
