// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/**
 * Versioned wire contract for the device-pairing QR code generated by
 * `cli devices pair --kind ios` and scanned by the iOS app.
 *
 * Previously the contract lived in two places — the producer
 * (`cli/src/commands/devices.ts`) hand-stringified `JSON.stringify({
 * v: 2, gatewayUrl, pairingCode })`, and the consumer
 * (`ios/Sources/Omnesis/Pairing/PairingPayload.swift`) had its own
 * Codable struct mirror with no shared schema. Bumping the wire shape
 * (e.g. add a TLS fingerprint field, switch to a different exchange
 * code) required the operator to remember to update both sides; a
 * mismatch produced a generic "invalid shape" error in the iOS app
 * with no signal to the CLI author.
 *
 * Now both ends derive from this module:
 *
 * - Pairing issuers use the versioned builders to produce the JSON
 *   string that gets QR-encoded.
 * - The gateway imports `PAIRING_PROTOCOL_VERSION` to advertise its
 *   max-supported version (future server-side use; today the gateway
 *   doesn't decode QR payloads itself).
 * - The TS-side `decodePairingPayload()` mirrors the Swift decoder's
 *   error envelope so a future native iOS-rewrite or Mac client can
 *   drop straight in.
 *
 * The Swift side keeps its hand-written `PairingPayload` Codable
 * mirror (manually maintained); the contract here is the source of truth, the Swift
 * side stays in sync via grep.
 */

/** The current QR-payload version understood by Omnesis clients. */
export const PAIRING_PROTOCOL_VERSION = 4 as const;
/** Oldest QR-payload version retained by the decoders. */
export const PAIRING_PROTOCOL_MIN_VERSION = 1 as const;

export type PairingTlsTrust =
  | { readonly mode: "system" }
  | { readonly mode: "pinned-leaf"; readonly fingerprint: string };

/**
 * V4 makes the TLS trust policy explicit. Public HTTPS gateways use normal
 * WebPKI hostname verification; private gateways retain leaf-certificate
 * pinning for their self-signed certificate.
 */
export interface PairingPayloadV4 {
  v: 4;
  gatewayUrl: string;
  pairingCode: string;
  tls: PairingTlsTrust;
}

/**
 * V3 (legacy). Adds the gateway's TLS leaf-cert SHA-256 fingerprint
 * (lowercase hex, no colons) so the iOS app can pin it on first
 * connect (TOFU). Required for HTTPS-by-default — the gateway's
 * auto-generated self-signed cert wouldn't validate against system
 * trust.
 */
export interface PairingPayloadV3 {
  v: 3;
  gatewayUrl: string;
  pairingCode: string;
  /** Lowercase hex SHA-256 of the gateway's TLS leaf cert (64 chars). */
  fingerprint: string;
}

/**
 * V2 (legacy, no pinning). The QR carries only the gateway URL + a
 * short pairing code; the iOS app POSTs `{pairingCode}` to
 * `/devices/pair` to exchange it for a device row + token. Kept for
 * back-compat with older gateways.
 */
export interface PairingPayloadV2 {
  v: 2;
  gatewayUrl: string;
  pairingCode: string;
}

/**
 * V1 (legacy). Pre-rearchitecture shape — the QR carried a
 * pre-issued token directly. Kept so a stale QR from an old build
 * still parses cleanly with a recognisable error rather than a
 * generic "invalid shape" failure.
 */
export interface PairingPayloadV1 {
  v: 1;
  url: string;
  token: string;
  accountId: string;
  name: string;
}

export type PairingPayload =
  | PairingPayloadV4
  | PairingPayloadV3
  | PairingPayloadV2
  | PairingPayloadV1;

export type PairingPayloadDecodeError =
  | { kind: "invalid-json" }
  | { kind: "invalid-shape"; detail: string }
  | { kind: "unsupported-version"; version: number }
  | { kind: "invalid-url" }
  | { kind: "invalid-scheme"; scheme: string }
  | { kind: "invalid-fingerprint" }
  | { kind: "missing-field"; field: string };

/** Lowercase-hex SHA-256: exactly 64 characters from `[0-9a-f]`. */
const FINGERPRINT_PATTERN = /^[0-9a-f]{64}$/;

/** Allowed URL schemes for `gatewayUrl`. Mirrors the Swift allowlist. */
const ALLOWED_SCHEMES = new Set(["http:", "https:"]);

/**
 * Build a V3 pairing payload. Centralised so the CLI doesn't drift
 * on the field order or version constant.
 */
export function buildPairingPayloadV3(args: {
  gatewayUrl: string;
  pairingCode: string;
  fingerprint: string;
}): PairingPayloadV3 {
  return {
    v: 3,
    gatewayUrl: args.gatewayUrl,
    pairingCode: args.pairingCode,
    fingerprint: args.fingerprint,
  };
}

/** Build an explicitly trusted V4 payload. */
export function buildPairingPayloadV4(args: {
  gatewayUrl: string;
  pairingCode: string;
  tls: PairingTlsTrust;
}): PairingPayloadV4 {
  return {
    v: PAIRING_PROTOCOL_VERSION,
    gatewayUrl: args.gatewayUrl,
    pairingCode: args.pairingCode,
    tls: args.tls,
  };
}

/**
 * Build a V2 pairing payload. Kept for back-compat with operators on
 * older HTTP-only gateways; new pairings should use
 * `buildPairingPayloadV3`.
 */
export function buildPairingPayloadV2(args: {
  gatewayUrl: string;
  pairingCode: string;
}): PairingPayloadV2 {
  return {
    v: 2,
    gatewayUrl: args.gatewayUrl,
    pairingCode: args.pairingCode,
  };
}

/**
 * Parse a raw QR-decoded string (or JSON blob from the manual-entry
 * sheet) into a typed pairing payload. Mirrors the error cases the
 * Swift `PairingPayload.decode` raises.
 */
export function decodePairingPayload(
  raw: string,
): { ok: true; payload: PairingPayload } | { ok: false; error: PairingPayloadDecodeError } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw.trim());
  } catch {
    return { ok: false, error: { kind: "invalid-json" } };
  }
  if (!parsed || typeof parsed !== "object") {
    return {
      ok: false,
      error: { kind: "invalid-shape", detail: "top-level value is not an object" },
    };
  }
  const v = (parsed as { v?: unknown }).v;
  if (typeof v !== "number") {
    return {
      ok: false,
      error: { kind: "invalid-shape", detail: "missing or non-numeric `v` field" },
    };
  }
  if (v === 4) {
    const obj = parsed as Partial<PairingPayloadV4>;
    const baseError = validateExchangeFields(obj.gatewayUrl, obj.pairingCode);
    if (baseError) return { ok: false, error: baseError };
    // validateExchangeFields establishes these invariants, but TypeScript cannot
    // narrow object properties across that helper boundary.
    const gatewayUrl = obj.gatewayUrl as string;
    const pairingCode = obj.pairingCode as string;
    if (new URL(gatewayUrl).protocol !== "https:") {
      return { ok: false, error: { kind: "invalid-scheme", scheme: "http" } };
    }
    const tls = obj.tls;
    if (!tls || typeof tls !== "object" || !("mode" in tls)) {
      return { ok: false, error: { kind: "missing-field", field: "tls" } };
    }
    if (tls.mode === "system") {
      return {
        ok: true,
        payload: {
          v: 4,
          gatewayUrl,
          pairingCode,
          tls: { mode: "system" },
        },
      };
    }
    if (tls.mode === "pinned-leaf") {
      if (!("fingerprint" in tls) || typeof tls.fingerprint !== "string") {
        return { ok: false, error: { kind: "missing-field", field: "tls.fingerprint" } };
      }
      if (!FINGERPRINT_PATTERN.test(tls.fingerprint)) {
        return { ok: false, error: { kind: "invalid-fingerprint" } };
      }
      return {
        ok: true,
        payload: {
          v: 4,
          gatewayUrl,
          pairingCode,
          tls: { mode: "pinned-leaf", fingerprint: tls.fingerprint },
        },
      };
    }
    return { ok: false, error: { kind: "invalid-shape", detail: "unknown TLS trust mode" } };
  }
  if (v === 3) {
    const obj = parsed as Partial<PairingPayloadV3>;
    if (typeof obj.gatewayUrl !== "string" || obj.gatewayUrl.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "gatewayUrl" } };
    if (typeof obj.pairingCode !== "string" || obj.pairingCode.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "pairingCode" } };
    if (typeof obj.fingerprint !== "string" || obj.fingerprint.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "fingerprint" } };
    let url: URL;
    try {
      url = new URL(obj.gatewayUrl);
    } catch {
      return { ok: false, error: { kind: "invalid-url" } };
    }
    if (!ALLOWED_SCHEMES.has(url.protocol)) {
      return {
        ok: false,
        error: { kind: "invalid-scheme", scheme: url.protocol.replace(/:$/, "") },
      };
    }
    if (!FINGERPRINT_PATTERN.test(obj.fingerprint)) {
      return { ok: false, error: { kind: "invalid-fingerprint" } };
    }
    return {
      ok: true,
      payload: {
        v: 3,
        gatewayUrl: obj.gatewayUrl,
        pairingCode: obj.pairingCode,
        fingerprint: obj.fingerprint,
      },
    };
  }
  if (v === 2) {
    const obj = parsed as Partial<PairingPayloadV2>;
    if (typeof obj.gatewayUrl !== "string")
      return { ok: false, error: { kind: "missing-field", field: "gatewayUrl" } };
    if (obj.gatewayUrl.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "gatewayUrl" } };
    if (typeof obj.pairingCode !== "string")
      return { ok: false, error: { kind: "missing-field", field: "pairingCode" } };
    if (obj.pairingCode.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "pairingCode" } };
    let url: URL;
    try {
      url = new URL(obj.gatewayUrl);
    } catch {
      return { ok: false, error: { kind: "invalid-url" } };
    }
    if (!ALLOWED_SCHEMES.has(url.protocol)) {
      return {
        ok: false,
        error: { kind: "invalid-scheme", scheme: url.protocol.replace(/:$/, "") },
      };
    }
    return {
      ok: true,
      payload: { v: 2, gatewayUrl: obj.gatewayUrl, pairingCode: obj.pairingCode },
    };
  }
  if (v === 1) {
    const obj = parsed as Partial<PairingPayloadV1>;
    if (typeof obj.url !== "string" || obj.url.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "url" } };
    if (typeof obj.token !== "string" || obj.token.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "token" } };
    if (typeof obj.accountId !== "string" || obj.accountId.length === 0)
      return { ok: false, error: { kind: "missing-field", field: "accountId" } };
    if (typeof obj.name !== "string")
      return { ok: false, error: { kind: "missing-field", field: "name" } };
    let url: URL;
    try {
      url = new URL(obj.url);
    } catch {
      return { ok: false, error: { kind: "invalid-url" } };
    }
    if (!ALLOWED_SCHEMES.has(url.protocol)) {
      return {
        ok: false,
        error: { kind: "invalid-scheme", scheme: url.protocol.replace(/:$/, "") },
      };
    }
    return {
      ok: true,
      payload: { v: 1, url: obj.url, token: obj.token, accountId: obj.accountId, name: obj.name },
    };
  }
  return { ok: false, error: { kind: "unsupported-version", version: v } };
}

function validateExchangeFields(
  gatewayUrl: unknown,
  pairingCode: unknown,
): PairingPayloadDecodeError | null {
  if (typeof gatewayUrl !== "string" || gatewayUrl.length === 0) {
    return { kind: "missing-field", field: "gatewayUrl" };
  }
  if (typeof pairingCode !== "string" || pairingCode.length === 0) {
    return { kind: "missing-field", field: "pairingCode" };
  }
  let url: URL;
  try {
    url = new URL(gatewayUrl);
  } catch {
    return { kind: "invalid-url" };
  }
  if (!ALLOWED_SCHEMES.has(url.protocol)) {
    return { kind: "invalid-scheme", scheme: url.protocol.replace(/:$/, "") };
  }
  return null;
}
