// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/**
 * Integration proof for `applyCaTrustInProcess`: certificates added to
 * Node's default CA store via `tls.setDefaultCACertificates()` are picked
 * up by undici's `fetch`, the `WebSocket` global, and raw `node:tls`
 * connections in the SAME process — even after a prior connection to the
 * same host already failed TLS verification. This is what lets the TOFU
 * flow trust a gateway cert without re-exec'ing the process with
 * `NODE_EXTRA_CA_CERTS`.
 *
 * The test cert is generated by shelling out to `openssl`, mirroring the
 * gateway's own self-signed generation in `packages/gateway/src/tls.ts`.
 *
 * Runs under the vitest forks pool, so the CA-store mutation is confined
 * to this file's process and cannot leak into other test files.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { createServer, type Server } from "node:https";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { connect as tlsConnect, getCACertificates } from "node:tls";
import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { applyCaTrustInProcess, isTlsCertError } from "./tofu.js";

/** Generate a fresh RSA-2048 self-signed cert for localhost/127.0.0.1. */
function generateSelfSignedCert(
  dir: string,
  name: string,
): { certPath: string; keyPath: string; certPem: string } {
  const cnfPath = join(dir, `${name}.cnf`);
  const keyPath = join(dir, `${name}-key.pem`);
  const certPath = join(dir, `${name}-cert.pem`);
  const cnf = `
[req]
distinguished_name = dn
prompt = no
x509_extensions = v3_ext

[dn]
CN = ${name}

[v3_ext]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost, IP:127.0.0.1
`.trim();
  writeFileSync(cnfPath, cnf);
  execFileSync(
    "openssl",
    [
      "req",
      "-x509",
      "-newkey",
      "rsa:2048",
      "-keyout",
      keyPath,
      "-out",
      certPath,
      "-days",
      "3",
      "-nodes",
      "-config",
      cnfPath,
    ],
    { stdio: ["ignore", "ignore", "pipe"] },
  );
  return { certPath, keyPath, certPem: readFileSync(certPath, "utf8") };
}

/** Bind the server to the first free port in the integration-test range. */
async function listenInRange(server: Server): Promise<number> {
  for (let port = 17660; port <= 17699; port++) {
    try {
      await new Promise<void>((resolve, reject) => {
        server.once("error", reject);
        server.listen(port, "127.0.0.1", () => {
          server.removeListener("error", reject);
          resolve();
        });
      });
      return port;
    } catch (err) {
      if ((err as { code?: string }).code !== "EADDRINUSE") throw err;
    }
  }
  throw new Error("No free port in 17660-17699");
}

/** Open a WebSocket and resolve "open" or "error" (never rejects). */
function tryWebSocket(url: string): Promise<"open" | "error"> {
  return new Promise((resolve) => {
    const ws = new WebSocket(url);
    ws.onopen = () => {
      ws.close();
      resolve("open");
    };
    ws.onerror = () => resolve("error");
  });
}

let tmpDir: string;
let server: Server;
let port: number;
let certPath: string;

beforeAll(async () => {
  // Make the "fetch rejects first" assertion deterministic even in shells
  // where TLS verification was disabled globally.
  delete process.env.NODE_TLS_REJECT_UNAUTHORIZED;

  tmpDir = mkdtempSync(join(tmpdir(), "omnesis-tofu-int-"));
  const generated = generateSelfSignedCert(tmpDir, "tofu-integration-gateway");
  certPath = generated.certPath;

  server = createServer({ cert: generated.certPem, key: readFileSync(generated.keyPath) });
  server.on("request", (req, res) => {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ status: "ok", path: req.url }));
  });
  // Minimal RFC 6455 handshake so the undici WebSocket client can complete
  // an upgrade — enough to prove the TLS layer trusts the cert.
  server.on("upgrade", (req, socket) => {
    const accept = createHash("sha1")
      .update(`${req.headers["sec-websocket-key"]}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`)
      .digest("base64");
    socket.write(
      "HTTP/1.1 101 Switching Protocols\r\n" +
        "Upgrade: websocket\r\n" +
        "Connection: Upgrade\r\n" +
        `Sec-WebSocket-Accept: ${accept}\r\n\r\n`,
    );
  });
  port = await listenInRange(server);
}, 30_000);

afterAll(() => {
  server.closeAllConnections();
  server.close();
  rmSync(tmpDir, { recursive: true, force: true });
});

// The tests in this describe are order-dependent on purpose: the untrusted
// failures must be observed BEFORE applyCaTrustInProcess runs, in the same
// process — that is exactly the scenario the TOFU flow relies on.
describe("applyCaTrustInProcess — in-process trust without re-exec", () => {
  test("fetch and WebSocket reject the untrusted self-signed cert", async () => {
    const err = await fetch(`https://127.0.0.1:${port}/health`).then(
      () => null,
      (e: unknown) => e,
    );
    expect(err).not.toBeNull();
    expect(isTlsCertError(err)).toBe(true);

    await expect(tryWebSocket(`wss://127.0.0.1:${port}/`)).resolves.toBe("error");
  });

  test("after applyCaTrustInProcess, the SAME process's fetch succeeds", async () => {
    applyCaTrustInProcess(certPath);

    const res = await fetch(`https://127.0.0.1:${port}/health`);
    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({ status: "ok", path: "/health" });
  });

  test("the WebSocket global (undici) also connects", async () => {
    await expect(tryWebSocket(`wss://127.0.0.1:${port}/`)).resolves.toBe("open");
  });

  test("a raw node:tls connection verifies the cert", async () => {
    const authorized = await new Promise<boolean>((resolve, reject) => {
      const socket = tlsConnect({ host: "127.0.0.1", port, servername: "localhost" }, () => {
        const ok = socket.authorized;
        socket.destroy();
        resolve(ok);
      });
      socket.on("error", reject);
    });
    expect(authorized).toBe(true);
  });

  test("re-applying the same path is a no-op (idempotent)", () => {
    const before = getCACertificates("default").length;
    applyCaTrustInProcess(certPath);
    expect(getCACertificates("default").length).toBe(before);
  });

  test("applies rotated certificate content written at the same path", () => {
    const rotated = generateSelfSignedCert(tmpDir, "tofu-rotated-gateway");
    const before = getCACertificates("default").length;
    writeFileSync(certPath, rotated.certPem);
    applyCaTrustInProcess(certPath);
    expect(getCACertificates("default").length).toBe(before + 1);
  });

  test("multi-cert PEM bundles are split and each cert is added", () => {
    const a = generateSelfSignedCert(tmpDir, "tofu-bundle-a");
    const b = generateSelfSignedCert(tmpDir, "tofu-bundle-b");
    const bundlePath = join(tmpDir, "bundle.pem");
    writeFileSync(bundlePath, a.certPem + b.certPem);

    const before = getCACertificates("default").length;
    applyCaTrustInProcess(bundlePath);
    expect(getCACertificates("default").length).toBe(before + 2);
  });

  test("throws on a file with no PEM certificates", () => {
    const junkPath = join(tmpDir, "junk.pem");
    writeFileSync(junkPath, "not a certificate\n");
    expect(() => applyCaTrustInProcess(junkPath)).toThrow(/No PEM certificates found/);
  });
});
