// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath

/**
 * The worth gate's invented mail — the emails the `brain-decision-*` suites
 * push, each with the score the scripted decision model gives it.
 *
 * One table serves three consumers, so they cannot drift apart:
 *  - the scripted decision server's policy (score by subject);
 *  - the expected request a suite asserts the gate sent (built with the
 *    gateway's own rubric, `emailWorthState` + `EMAIL_WORTH_QUESTIONS`);
 *  - the committed replay cassettes under
 *    `evals/universes/loops-test-life/decision-cassettes/`, regenerated by
 *    `npx tsx scripts/write-worth-gate-cassettes.mjs` and held in sync by
 *    `worth-gate-mail.test.ts`.
 *
 * Everything here is invented: fictional senders on RFC-2606 reserved
 * domains, fictional vendors and places.
 */

import {
  formatDecisionCassetteEntry,
  type DecisionAnswer,
  type DecisionRequest,
} from "@omnesis/core";
import {
  EMAIL_WORTH_QUESTIONS,
  EMAIL_WORTH_QUESTION_ID,
  EMAIL_WORTH_THRESHOLD,
  emailWorthState,
} from "@omnesis/gateway/src/worth/rubric.js";
import { CAST } from "./docs.js";
import type { BenchDoc } from "./bench.js";

/** The model id cassettes record, as the TypeSafe backend reports it. */
export const WORTH_GATE_MODEL_ID = "jev-1.13.0";

export { EMAIL_WORTH_QUESTION_ID, EMAIL_WORTH_THRESHOLD };

export interface WorthMail {
  /** Stable key a suite refers to the email by. */
  key: string;
  externalId: string;
  title: string;
  content: string;
  sender: { name: string; email: string };
  /** The worth score the scripted model answers with (levels 0–3). */
  score: number;
}

/** The sender/recipient metadata the rubric reads the `from` line out of. */
function peopleOf(mail: WorthMail): Record<string, unknown>[] {
  return [
    { role: "sender", name: mail.sender.name, emails: [mail.sender.email] },
    { role: "recipient", name: CAST.self.name, emails: [CAST.self.email] },
  ];
}

export const WORTH_MAIL = {
  promotion: {
    key: "promotion",
    externalId: "wg-promo-1",
    title: "Autumn sale: 40% off trail gear this weekend only",
    content:
      "Stock up for the season. Tents, stoves and trail shoes are 40% off until Sunday at Stellar Outfitters. Browse the collection online and use code AUTUMN40 at checkout.",
    sender: { name: "Stellar Outfitters", email: "offers@stellar-outfitters.example.com" },
    score: 0.12,
  },
  newsletter: {
    key: "newsletter",
    externalId: "wg-news-1",
    title: "The Riverside Weekly — issue 42",
    content:
      "This week in the Riverside Weekly: a new bakery on the high street, the library's winter reading list, and results from the five-a-side league.",
    sender: { name: "Riverside Weekly", email: "digest@riverside-weekly.example.org" },
    score: 0.05,
  },
  booking: {
    key: "booking",
    externalId: "wg-booking-1",
    title: "Booking confirmed: Northstar Air flight NS 214 to Lisbon",
    content:
      "Your booking reference is QX7P2L. Flight NS 214 departs on 14 November at 07:40 from terminal 2. Online check-in opens 24 hours before departure. Your itinerary is attached.",
    sender: { name: "Northstar Air", email: "bookings@northstar-air.example.com" },
    score: 2.41,
  },
  friend: {
    key: "friend",
    externalId: "wg-friend-1",
    title: "Dinner next Friday?",
    content:
      "Hi Alex, are you free for dinner next Friday? I found a new place near the river and I would love to catch up before my trip. Let me know. Maya",
    sender: { name: CAST.maya.name, email: CAST.maya.email },
    score: 2.88,
  },
  receipt: {
    key: "receipt",
    externalId: "wg-receipt-1",
    title: "Your Studio Northstar order has shipped",
    content:
      "Order 55-1093 has left our warehouse and should arrive within three working days. Track the parcel from your account page.",
    sender: { name: "Studio Northstar", email: "orders@studio-northstar.example.com" },
    score: 1.02,
  },
  invitation: {
    key: "invitation",
    externalId: "wg-invite-1",
    title: "Board games at Jamie's on Saturday",
    content:
      "Hey Alex, a few of us are playing board games at mine on Saturday from 7pm. Bring a snack if you can. Jamie",
    sender: { name: CAST.jamie.name, email: CAST.jamie.email },
    score: 2.2,
  },
} as const satisfies Record<string, WorthMail>;

export type WorthMailKey = keyof typeof WORTH_MAIL;

/** The mail as a bench document: an email with a sender in `metadata.people`. */
export function worthMailDoc(mail: WorthMail, extra: Partial<BenchDoc> = {}): BenchDoc {
  return {
    externalId: mail.externalId,
    title: mail.title,
    content: mail.content,
    documentType: "email",
    ...extra,
    metadata: { people: peopleOf(mail), ...(extra.metadata ?? {}) },
  };
}

/**
 * An attachment of `parent`: an `attachment` document declaring its container
 * through `metadata.extra.parentExternalId`, the way an email provider emits
 * one. The worth gate judges it by the parent email.
 */
export function attachmentOf(parent: WorthMail, externalId: string, title: string): BenchDoc {
  return {
    externalId,
    title,
    content: `Itinerary for ${parent.title}. Passenger: ${CAST.self.name}.`,
    documentType: "attachment",
    metadata: { extra: { parentExternalId: parent.externalId } },
  };
}

/** The exact request the worth gate sends for `mail` — built with the gateway's rubric. */
export function worthRequestFor(mail: WorthMail): DecisionRequest {
  return {
    state: emailWorthState({
      title: mail.title,
      content: mail.content,
      metadata: { people: peopleOf(mail) },
    }),
    questions: EMAIL_WORTH_QUESTIONS,
  };
}

/** The answers the scripted model gives `mail`. */
export function worthAnswersFor(mail: WorthMail): Record<string, DecisionAnswer> {
  const clamped = Math.max(0, Math.min(3, mail.score));
  // A two-level split around the score, so `probabilities` is a coherent
  // distribution whose expectation is the score.
  const floor = Math.min(2, Math.floor(clamped));
  const upper = clamped - floor;
  const probabilities: Record<string, number> = { "0": 0, "1": 0, "2": 0, "3": 0 };
  probabilities[String(floor)] = round(1 - upper);
  probabilities[String(floor + 1)] = round(upper);
  return {
    [EMAIL_WORTH_QUESTION_ID]: { type: "score", score: mail.score, confidence: 0.9, probabilities },
  };
}

function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

/** The mail whose subject is `subject`, or undefined. */
export function worthMailBySubject(subject: unknown): WorthMail | undefined {
  return Object.values(WORTH_MAIL).find((m) => m.title === subject);
}

/** Whether the gate lets `mail` through to an agent run. */
export function passesWorthGate(mail: WorthMail): boolean {
  return mail.score >= EMAIL_WORTH_THRESHOLD;
}

/**
 * The replay cassette for every mail in {@link WORTH_MAIL}, one line each, in
 * table order — the content of
 * `evals/universes/loops-test-life/decision-cassettes/worth-gate.jsonl`.
 */
export function worthGateCassetteLines(): string[] {
  return Object.values(WORTH_MAIL).map((mail) =>
    formatDecisionCassetteEntry(worthRequestFor(mail), {
      model: WORTH_GATE_MODEL_ID,
      answers: worthAnswersFor(mail),
      inputTokens: 480,
    }),
  );
}
