// swift-tools-version:5.9
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Adrien Conrath
//
// Omnesis iOS source library.
//
// This declares a plain SwiftPM library so that non-UI logic (Pairing,
// Transport, Collector, AppleHealth schema/cursor/normalizer) is
// testable via `swift test` on macOS without an iOS simulator.
//
// The iOS app itself lives in `Omnesis.xcodeproj`, which references
// the same Sources/Omnesis directory and adds all the iOS-specific
// plumbing (signing, entitlements, Info.plist, HealthKit framework
// link). That Xcode project is generated from `project.yml` via
// XcodeGen — see ios/README.md.
//
// Open with: `open Package.swift` (for CLI testing).
// Build the app with: `open Omnesis.xcodeproj` (generated by
// `xcodegen generate`).

import PackageDescription

let package = Package(
    name: "Omnesis",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "Omnesis", targets: ["Omnesis"]),
    ],
    dependencies: [
        .package(url: "https://github.com/swhitty/SwiftDraw.git", exact: "0.29.0"),
    ],
    targets: [
        .target(
            name: "Omnesis",
            dependencies: ["SwiftDraw"],
            path: "Sources/Omnesis",
            exclude: [
                // DEBUG-only simulator probe; never part of the sim-less lane.
                "Notifications/PushSpikeInspector.swift",
            ]
        ),
        // The PURE-LOGIC test lane: `swift test` builds + runs this target
        // natively for macOS (no simulator, no Xcode project) so a logic change
        // gets sub-minute feedback — the C11 shift-left lane, driven by
        // scripts/ios-logic.sh. The iOS-only UI is `#if canImport(UIKit)`-
        // compiled-out of the Omnesis library on macOS, so the tests that
        // exercise UIKit/SwiftUI views (or a live gateway) cannot compile/run
        // here and are excluded. The full suite — including these — still runs
        // via `xcodebuild test` against the Xcode project (project.yml's
        // OmnesisTests bundle target), which scripts/ios-snapshot.sh drives on
        // the simulator. Keep these two lists in sync: a new UIKit-touching or
        // live-gateway test must be added here so the logic lane stays sim-less.
        .testTarget(
            name: "OmnesisTests",
            dependencies: ["Omnesis"],
            path: "Tests/OmnesisTests",
            exclude: [
                // Renders SwiftUI views to PNGs — needs UIKit (iOS only).
                "PreviewSnapshotTests.swift",
                // Exercises AppearanceStore, which is UIKit-gated in the library.
                "AppearanceTests.swift",
                // Exercises GatewayErrorView (a SwiftUI view), UIKit-gated.
                "GatewayErrorViewTests.swift",
                // Exercises AdminCoordinator (a UIKit-gated coordinator).
                "AdminCoordinatorReconnectTests.swift",
                "AdminCoordinatorPendingAccessTests.swift",
                "AdminCoordinatorInternalSourcesTests.swift",
                "AdminCoordinatorNoticesTests.swift",
                // Constructs HealthSampleProbeView (SwiftUI + UIKit-gated).
                "HealthSampleProbeViewTests.swift",
                // Drives the transport clients against a spawned live gateway.
                "GatewayLiveE2ETests.swift",
            ]
        ),
    ]
)
